name: Tests

on:
  pull_request:
    branches:
      - master
      - ru
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - master
      - ru
  workflow_dispatch:

env:
  UV_PYTHON: 3.13

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v6

      - name: Run tests
        run: uv run pytest tests -q
